baseurl = "/"
enableEmoji = true
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
title = "sommlid.rocks"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
posts = "/posts/:year/:month/:day/:slug/"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2
[[menu.feed]]
name = "Subscribe"
url = "/index.xml"

[params]
custom_css = ["css/theme-override.css"]
description = "Sommlid's music blog."
footer = "[Privacy Policy](https://sommlid.rocks/privacy/) | [mail@sommlid.rocks](mailto:mail@sommlid.rocks)"
